### ISSUE TITLE
Toolchain version 2.8.0 is broken

### ISSUE THREAD

**Issue by mshabunin** [XUANTIE-RV/binutils-gdb#3]
Last commit on branch https://github.com/T-head-Semi/binutils-gdb/tree/xuantie-binutils-gdb-2.35  breaks `gdb/arch/riscv.h` ([diff](https://github.com/T-head-Semi/binutils-gdb/commit/66d5fa3a5aea033a6822bdcaf85e31c48048280d#diff-e1a355c7a98972827829f26da1483c7c2034f02d3d92ab14a402fee8312afd3c)):
```
In file included from /xuantie-gnu-toolchain/riscv-gdb/gdb/arch/riscv.c:19:
/xuantie-gnu-toolchain/riscv-gdb/gdb/arch/riscv.h:103:2: error: #endif without #if
  103 | #endif /* ARCH_RISCV_H */
      |  ^~~~~
```

**Comment by Lifang-XIA** [comment]
Updated
https://github.com/T-head-Semi/binutils-gdb/commit/3f1c1bda96771d78453da163ef7aedca540d0f18

**Comment by JF002** [comment]
Thanks for the fix! I can now successfully build [xuantie-gnu-toolchain](https://github.com/T-head-Semi/xuantie-gnu-toolchain) on a AARCH64 host!
